version: "3.9"
services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - ./nats_data:/data/jetstream
    command: ["-c", "/etc/nats/nats.conf"]
    restart: unless-stopped

volumes:
  nats_data:
    driver: local
