name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:2.10.21-alpine
        ports:
          - "4222:4222"
          - "8222:8222"
        command: [
          "-js",
          "--store_dir", "/data/jetstream",
          "--http_port", "8222",
          "--server_name", "nats-server",
          "--user", "ruser",
          "--password", "T0pS3cr3t"
        ]
      python39:
        image: python:3.9-alpine
        options: --entrypoint ""
      python310:
        image: python:3.10-alpine
        options: --entrypoint ""
      python311:
        image: python:3.11-alpine
        options: --entrypoint ""

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run Flake8
        run: |
          flake8  # Запуск линтера Flake8

      - name: Run Tests
        run: |
          python${{ matrix.python-version }} -m pytest --cov=src/nats_queue --cov-report=html src/test/
